name: bluequest_app
description: "BlueQuest - app de desafios"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localization: ^0.3.3
  intl: ^0.20.2
  dio: ^5.9.0
  flutter_riverpod: ^2.6.1
  go_router: ^16.2.0
  equatable: ^2.0.7
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
